// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTDGVCgRPQOYMs0RurWUCg660_AySxXc',
    appId: '1:69244349834:android:98ce999fda7c6920e16c73',
    messagingSenderId: '69244349834',
    projectId: 'lenrx-e760a',
    databaseURL: 'https://lenrx-e760a-default-rtdb.firebaseio.com',
    storageBucket: 'lenrx-e760a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQb8WeUe_vlbXumXynnuHDQhMuUom4GJM',
    appId: '1:69244349834:ios:6890a3fcca42d9bbe16c73',
    messagingSenderId: '69244349834',
    projectId: 'lenrx-e760a',
    databaseURL: 'https://lenrx-e760a-default-rtdb.firebaseio.com',
    storageBucket: 'lenrx-e760a.appspot.com',
    iosClientId: '69244349834-0518rkshtsjsdbmmbbsgg0h487n4j0j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hvu',
  );
}
